# Define local variables accessible throughout the Terragrunt configuration
locals {
  # Specify the AWS region to be used
  region = "eu-north-1"
}

# Configure the backend for storing Terraform state
remote_state {
  # Use the local backend (state is stored on disk locally)
  backend = "local"
  config = {
    # Define the path for the local state file, relative to this file
    path = "${path_relative_to_include()}/terraform.tfstate"
  }
}

# Automatically generate a provider block for Terraform
generate "provider" {
  # Name of the generated file
  path      = "provider.tf"

  # Overwrite the file if it already exists (generated by Terragrunt)
  if_exists = "overwrite_terragrunt"

  # The content of the generated provider.tf file
  contents  = <<EOF
provider "aws" {
  region = "${local.region}"
}
EOF
}
